#define DYNAMIC_KEYMAP_LAYER_COUNT 6

#define COMBO_TERM 50
#define COMBO_MUST_HOLD_PER_COMBO

// #define TAPPING_TOGGLE 2

#undef ONESHOT_TIMEOUT
#define ONESHOT_TIMEOUT 1000

#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY

#define IGNORE_MOD_TAP_INTERRUPT
#define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
// #define PERMISSIVE_HOLD

// #define TAPPING_FORCE_HOLD
// #define TAPPING_FORCE_HOLD_PER_KEY

#define HOLD_ON_OTHER_KEY_PRESS
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

// #undef TAP_CODE_DELAY
// #define TAP_CODE_DELAY 5
// #define TAP_HOLD_CAPS_DELAY 0

// #define BILATERAL_COMBINATIONS

// #define AUTO_SHIFT_REPEAT
// #define AUTO_SHIFT_NO_AUTO_REPEAT
// #define RETRO_SHIFT 300
// #define AUTO_SHIFT_MODIFIERS

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD

// Mouse key speed and acceleration.
#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL

#define MK_C_OFFSET_UNMOD 6
#define MK_C_OFFSET_1 3

#define MK_W_INTERVAL_UNMOD 80
